# Generated by Django 4.0.3 on 2023-07-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_document_newuser_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='docname',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
