# Generated by Django 4.0.3 on 2023-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_newuser_docname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='docname',
        ),
        migrations.AddField(
            model_name='document',
            name='docname',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
